name: "ci-cd pipeline"

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: CI="" npm run build
      - name: Deploy
        # uses: actions/checkout@v3
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_BUILD_KEY }}

